# Generated by Django 4.2.2 on 2023-06-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(blank=True, choices=[(1, '*'), (2, ' *  * '), (3, ' *  *  * '), (4, ' *  *  *  * '), (5, ' *  *  *  *  * ')], null=True),
        ),
    ]
