# Generated by Django 4.2.2 on 2023-07-19 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='favorite',
        ),
    ]
